### ISSUE TITLE
performance improvement

### ISSUE THREAD

**Issue by ketzal88** [ketzal88/pokeFinder-with-API-Node-React-Express#6]
call the api once and save the data in that variable once and do the filter from there and not the filter each time a search is made

**Comment by codybarr** [comment]
@ketzal88 I can take a stab at this one.

**Comment by omniboyOK** [comment]
I'm sending a pr soon, assign me

**Comment by ketzal88** [comment]
> @ketzal88 I can take a stab at this one.

is already done, every one is hurry up thanks
